### ISSUE TITLE
https://zellwk.com/blog/crud-express-mongodb/ article is out of date

### ISSUE THREAD

**Issue by domluther** [zellwk/zellwk.com#222]
Hi this article is really useful, but has some parts that could do with being updated. I went through and made the following notes. Mind if I update the article and send a pull request?

Using Express
- mentions to use --save, no longer needed to add as a dependency since before npm5

https://betterstack.com/community/questions/what-is-save-option-for-npm-install/
https://dev.to/dailydevtips1/you-don-t-need-save-anymore-for-npm-installs-4min

- CRUD - CREATE section
- Says to install body-parser with --save
- no need to --save
- no longer a need to use body-parser. Instead...
app.use(express.urlencoded({ extended: true }));

- MongoDB
- Says to install mongodb with --save, no need to --save

MongoDB website UI is different
- How to create a new project - Didn't seem to be under the context in the top left-hand corner.
- Way of connecting to MongoDB has changed - not the same 'connect your application' option it is now under drivers

- Old style callback way of calling MongoClient.connect() section needs removing and leaving the promise version.
- Promise version needs updating.

(node:33911) [MONGODB DRIVER] Warning: useUnifiedTopology is a deprecated option: useUnifiedTopology has no effect since Node.js Driver version 4.0.0 and will be removed in the next major version
(Use `node --trace-warnings ...` to show where the warning was created)

- Remove the useUnifiedToplogy option from the object as deprecated

Using EJS
- Says to install ejs with --save, no need to --save

Accepting the PUT request
- app.use(bodyParser.json())
- Should change to express.json()

**Comment by zellwk** [comment]
@domluther Thank you for making these notes. I'd love it if you could go through the article and make a PR to update it. 

But there are a couple of things to note: 

1. `--save` is necessary because it saves dependencies into the `package.json` file. Without saving the dependencies, you won't be able to `npm install` when you need the packages afterwards. I don't recall seeing changes in this behaviour. 
2. What you mentioned about border parser and express is true — it'll be great if you could update those. 
3. What you mentioned about `useUnifiedTogology` is also true. Again, it would be great if you could update those. 
4. Regarding the MongoDB website UI, I'll need you to take new screenshots if you don't mind — it's been ages since I logged on to that site and I've no idea what has changed.

**Comment by zellwk** [comment]
@domluther Oh great. It has changed and I didn't know it. Then good, please proceed and remove `--save` from the article as well. Thanks!

**Comment by domluther** [comment]
https://github.com/zellwk/zellwk.com/pull/224 I went through and believe I've fixed the issues I flagged up.

**Comment by zellwk** [comment]
Thank you. Let's converse directly on the PR. Will be closing this issue.
